DROP TABLE BOARD_UPLOAD_FILE;
DROP TABLE BOARD;
DROP TABLE BOARD_CATEGORY;

CREATE TABLE BOARD (
	BOARD_ID 		NUMBER CONSTRAINT PK_BOARD_BOARD_ID PRIMARY KEY,
	CATEGORY_ID 	NUMBER,
	WRITER 			VARCHAR2(20) 	NOT NULL,
	EMAIL 			VARCHAR2(100),
	PASSWORD 		VARCHAR2(20) 	NOT NULL,
	TITLE 			VARCHAR2(500) 	NOT NULL,
	CONTENT 		CLOB,
	WRITE_DATE 		DATE DEFAULT SYSDATE NOT NULL,
	MASTER_ID 		NUMBER,
	REPLY_NUMBER 	NUMBER,
	REPLY_STEP 		NUMBER,
	READ_COUNT 		NUMBER DEFAULT 0
);

CREATE TABLE BOARD_CATEGORY (
	CATEGORY_ID 		NUMBER CONSTRAINT PK_BOARD_CATEGORY_ID PRIMARY KEY,
	CATEGORY_NAME 		VARCHAR2(100) NOT NULL,
	CATEGORY_DESCRIPTION VARCHAR2(100) NULL
);

CREATE TABLE BOARD_UPLOAD_FILE (
	FILE_ID 			NUMBER CONSTRAINT PK_BOARD_FILE_ID PRIMARY KEY,
	BOARD_ID			NUMBER NULL,
	FILE_NAME 			VARCHAR2(235) NULL,
	FILE_SIZE 			VARCHAR2(45) NULL,
	FILE_CONTENT_TYPE 	VARCHAR2(500) NULL,
	FILE_DATA 			BLOB NULL
);

ALTER TABLE BOARD_CATEGORY 
 ADD CONSTRAINT UK_BOARD_CATEGORY_NAME UNIQUE (CATEGORY_NAME) 
 USING INDEX;

ALTER TABLE BOARD 
  ADD CONSTRAINT FK_BOARD_CATEGORY_ID
    FOREIGN KEY (CATEGORY_ID) REFERENCES BOARD_CATEGORY (CATEGORY_ID);

ALTER TABLE BOARD_UPLOAD_FILE 
  ADD CONSTRAINT FK_BOARD_BOARD_ID
    FOREIGN KEY (BOARD_ID) REFERENCES BOARD (BOARD_ID);